// Generated by Xata Codegen 0.29.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "game",
    columns: [
      { name: "score_factor", type: "float" },
      { name: "turn", type: "int", defaultValue: "0" },
      { name: "progress", type: "float", defaultValue: "0" },
      { name: "starting_country", type: "link", link: { table: "country" } },
      { name: "company", type: "link", link: { table: "company" } },
      { name: "world", type: "link", link: { table: "world" } },
    ],
  },
  {
    name: "country",
    columns: [
      { name: "name", type: "string" },
      { name: "gdp", type: "float" },
    ],
    revLinks: [
      { column: "starting_country", table: "company" },
      { column: "starting_country", table: "game" },
    ],
  },
  {
    name: "company",
    columns: [
      { name: "name", type: "string" },
      { name: "starting_country", type: "link", link: { table: "country" } },
      { name: "company_type", type: "string", defaultValue: "manufacturing" },
    ],
    revLinks: [
      { column: "company", table: "game" },
      { column: "company", table: "action" },
    ],
  },
  {
    name: "action",
    columns: [
      { name: "company", type: "link", link: { table: "company" } },
      { name: "data", type: "json" },
      { name: "type", type: "string", notNull: true, defaultValue: "invest" },
    ],
  },
  {
    name: "environment",
    columns: [
      { name: "celsius_increase", type: "float", defaultValue: "0" },
      { name: "deforestation", type: "float", defaultValue: "100" },
      { name: "ocean_biodiversity", type: "float", defaultValue: "100" },
      { name: "land_biodiversity", type: "float", defaultValue: "100" },
      { name: "sea_level_rise", type: "float", defaultValue: "0" },
      { name: "ozone", type: "float", defaultValue: "100" },
      { name: "microplastics", type: "int", defaultValue: "0" },
      { name: "oil_spills", type: "multiple" },
      { name: "natural_disasters", type: "multiple" },
    ],
    revLinks: [{ column: "environment", table: "world" }],
  },
  {
    name: "world",
    columns: [
      { name: "environment", type: "link", link: { table: "environment" } },
    ],
    revLinks: [{ column: "world", table: "game" }],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Game = InferredTypes["game"];
export type GameRecord = Game & XataRecord;

export type Country = InferredTypes["country"];
export type CountryRecord = Country & XataRecord;

export type Company = InferredTypes["company"];
export type CompanyRecord = Company & XataRecord;

export type Action = InferredTypes["action"];
export type ActionRecord = Action & XataRecord;

export type Environment = InferredTypes["environment"];
export type EnvironmentRecord = Environment & XataRecord;

export type World = InferredTypes["world"];
export type WorldRecord = World & XataRecord;

export type DatabaseSchema = {
  game: GameRecord;
  country: CountryRecord;
  company: CompanyRecord;
  action: ActionRecord;
  environment: EnvironmentRecord;
  world: WorldRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Jack-McGregor-s-workspace-bt62hk.eu-central-1.xata.sh/db/neoliberal-game",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
